$(document).ready(function(){
    $('.food-slider').slick({
        autoplay:true,
        slidesToShow:3,
        slidesToScroll:1,
        prewArrow:".prev-btn",
        nextArrow:".next-btn",
    });
});
